# Generated by Django 5.1.5 on 2025-01-23 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_aboutus_feedback_itemlist_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Image',
            field=models.ImageField(upload_to='items/'),
        ),
    ]
