# Generated by Django 5.1.5 on 2025-02-04 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='feedback_images/'),
        ),
    ]
