# Generated by Django 5.1.5 on 2025-02-04 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_feedback_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='User_name',
            field=models.CharField(max_length=100),
        ),
    ]
