# Generated by Django 5.1.5 on 2025-02-06 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_feedback_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Item_name',
            new_name='name',
        ),
    ]
