# Generated by Django 5.1.5 on 2025-02-06 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_item_name_item_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Price',
            new_name='price',
        ),
    ]
