# Generated by Django 5.1.5 on 2025-02-06 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_price_item_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Image',
            new_name='image',
        ),
    ]
